language: cpp
dist: bionic
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev
  - sudo apt-get install libzeroc-ice-dev libzeroc-ice3.7
script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
