language: cpp
sudo: true
dist: bionic
compiler:
  - gcc
  - clang
before_install:
  - apt-key adv --keyserver keyserver.ubuntu.com --recv B6391CB2CFBA643D
  - apt-add-repository "deb http://zeroc.com/download/ice/3.7/ubuntu18.04 stable main"
  - apt-get update
  - apt-get -y install libxml2-dev
  - apt-get install libzeroc-ice-dev libzeroc-ice3.7
