language: cpp
dist: bionic
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev
  - sudo apt-get install libzeroc-ice-dev libzeroc-ice3.7
  script:
  - cmake && make
